# Generated by Django 2.2.2 on 2019-07-31 03:26

from django.db import migrations, models
import django.db.models.deletion
import events.image_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('event_picture', models.URLField(blank=True, null=True)),
                ('event_logo', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(default='to be determined', max_length=100)),
                ('team_event', models.BooleanField(default=False)),
                ('max_participants', models.IntegerField(default=20)),
                ('reserved_slots', models.IntegerField(default=0, help_text='No of participant slots reserved for external players')),
                ('category', models.ManyToManyField(related_name='events', to='events.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SoloEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.Event')),
            ],
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='TeamEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.Event')),
                ('min_team_size', models.IntegerField(default=1)),
                ('max_team_size', models.IntegerField(default=1)),
            ],
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='ImageUploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=100)),
                ('upload_picture_path', models.CharField(max_length=250)),
                ('upload_logo_path', models.CharField(max_length=250)),
                ('forced_filename', models.CharField(blank=True, max_length=80, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('uploaded_picture', models.ImageField(upload_to=events.image_models.set_file_upload_picture_path)),
                ('uploaded_logo', models.ImageField(upload_to=events.image_models.set_file_upload_logo_path)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileUploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=100)),
                ('upload_picture_path', models.CharField(max_length=250)),
                ('upload_logo_path', models.CharField(max_length=250)),
                ('forced_filename', models.CharField(blank=True, max_length=80, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('uploaded_file', models.FileField(upload_to=events.image_models.set_file_upload_picture_path)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(related_name='events', to='events.Tags'),
        ),
    ]
