# Generated by Django 2.2.2 on 2019-07-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants_waiting_list',
        ),
        migrations.AddField(
            model_name='tags',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tags',
            name='name',
            field=models.CharField(default='for_events', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
