# Generated by Django 2.2.2 on 2019-07-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190706_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='for_events', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
